CREATE TABLE IF NOT EXISTS usuarios(
	id UUID PRIMARY KEY,
  	nome VARCHAR(45) NOT NULL,
  	email VARCHAR(45) NOT NULL UNIQUE,
  	isAdm BOOLEAN NOT NULL,
  	password VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS enderecos(
	id UUID PRIMARY KEY,
  	rua VARCHAR(25) NOT NULL,
  	cep VARCHAR(11) NOT NULL,
  	numero VARCHAR(6) NOT NULL,
  	cidade VARCHAR(25) NOT NULL,
  	usuario_id UUID NOT NULL,
  	FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);